# Core role - Base system setup, Homebrew installation
# This role sets up the foundation for all other roles

- name: Initialize variables
  ansible.builtin.set_fact:
    os_family: "{{ ansible_os_family }}"
    is_macos: "{{ ansible_os_family == 'Darwin' }}"
    is_linux: "{{ ansible_os_family != 'Darwin' }}"
  tags: [always]

- name: Detect Homebrew path (macOS architecture-specific)
  block:
    - name: Check for ARM64 Homebrew (Apple Silicon)
      ansible.builtin.stat:
        path: "/opt/homebrew/bin/brew"
      register: arm64_homebrew
      when: is_macos

    - name: Check for x86_64 Homebrew (Intel)
      ansible.builtin.stat:
        path: "/usr/local/bin/brew"
      register: x86_homebrew
      when: is_macos

    - name: Set homebrew_prefix for macOS (ARM64)
      ansible.builtin.set_fact:
        homebrew_prefix: "/opt/homebrew"
      when: is_macos and arm64_homebrew.stat.exists

    - name: Set homebrew_prefix for macOS (Intel)
      ansible.builtin.set_fact:
        homebrew_prefix: "/usr/local"
      when: is_macos and x86_homebrew.stat.exists and not arm64_homebrew.stat.exists

    - name: Set homebrew_prefix for Linux
      ansible.builtin.set_fact:
        homebrew_prefix: "/home/linuxbrew/.linuxbrew"
      when: is_linux
  tags: [always, homebrew]

- name: Set user and home from environment
  ansible.builtin.set_fact:
    current_user: "{{ lookup('env', 'USER') or lookup('env', 'LOGNAME') or 'root' }}"
    home_dir: "{{ lookup('env', 'HOME') or '/root' }}"
  tags: [always]

- name: Create devkit directories
  ansible.builtin.file:
    path: "{{ home_dir }}/.devkit/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - logs
    - backups
    - plugins
    - config
  tags: [always, setup]

- name: Check if Homebrew is installed
  ansible.builtin.stat:
    path: "{{ homebrew_prefix }}/bin/brew"
  register: homebrew_check
  tags: [always, homebrew]

- name: Install Homebrew
  ansible.builtin.shell: |
    set -o pipefail
    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | \
      /bin/bash 2>&1 | tee /tmp/homebrew_install.log
  register: homebrew_install
  when: not homebrew_check.stat.exists
  retries: 3
  delay: 5
  until: homebrew_install is succeeded
  changed_when: true
  failed_when: homebrew_install.rc != 0
  tags: [homebrew]

- name: Verify Homebrew installation
  ansible.builtin.stat:
    path: "{{ homebrew_prefix }}/bin/brew"
  register: homebrew_verify
  tags: [homebrew]

- name: Update Homebrew
  ansible.builtin.shell: "{{ homebrew_prefix }}/bin/brew update"
  changed_when: false
  when: homebrew_verify.stat.exists
  environment:
    PATH: "{{ homebrew_prefix }}/bin:{{ ansible_env.PATH }}"
  tags: [homebrew]

- name: Install core packages via Homebrew
  ansible.builtin.shell: |
    {{ homebrew_prefix }}/bin/brew install git curl wget
  changed_when: false
  environment:
    PATH: "{{ homebrew_prefix }}/bin:{{ ansible_env.PATH }}"
  tags: [homebrew, packages]

- name: Install Ansible (if needed)
  ansible.builtin.shell: |
    {{ homebrew_prefix }}/bin/brew install ansible
  changed_when: false
  when: ansible_version is not defined
  environment:
    PATH: "{{ homebrew_prefix }}/bin:{{ ansible_env.PATH }}"
  tags: [homebrew, packages]

- name: Create logging directory structure
  ansible.builtin.file:
    path: "{{ home_dir }}/.devkit/logs/archive"
    state: directory
    mode: '0755'
  tags: [setup, logging]

- name: Initialize setup log file
  ansible.builtin.copy:
    content: |
      # Mac-Setup Log
      # Started: {{ ansible_date_time.iso8601 }}
      # Platform: {{ os_family }}
      # User: {{ current_user }}
      # Host: {{ inventory_hostname }}

    dest: "{{ home_dir }}/.devkit/logs/setup.log"
    mode: '0644'
  changed_when: false
  tags: [setup, logging]

- name: Verify core tools are available
  ansible.builtin.shell: "{{ item }} --version"
  register: core_tools_check
  loop:
    - git
    - curl
    - "{{ homebrew_prefix }}/bin/brew"
  changed_when: false
  environment:
    PATH: "{{ ansible_env.PATH }}"
  tags: [validation]
