# Git Configuration Handlers
# Handles reloading and refreshing git configuration

- name: reload git config
  ansible.builtin.shell: |
    # Git reads config from files on each command invocation
    # So simply updating the files triggers reload
    git config --list > /dev/null
  environment:
    HOME: "{{ home_dir }}"
  changed_when: false
  tags: [git, reload]

- name: reload git hooks
  ansible.builtin.file:
    path: "{{ git_hooks_dir }}/{{ item }}"
    mode: '0755'
  loop:
    - pre-commit
    - commit-msg
    - post-commit
    - prepare-commit-msg
  tags: [git, hooks, reload]

- name: restart git services
  ansible.builtin.shell: |
    # Ensure git cache is cleared
    git config --list > /dev/null
  environment:
    HOME: "{{ home_dir }}"
  changed_when: false
  tags: [git, restart]
