---
# Pre-commit Framework Configuration for devkit
# Multi-language code quality enforcement
#
# Docs: https://pre-commit.com
# Setup: pre-commit install
# Test: pre-commit run --all-files
# Update: pre-commit autoupdate

default_language_version:
  python: python3.14

repos:
  # =========================================================================
  # General Checks (All Files)
  # =========================================================================
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # File format validation
      - id: check-json
      - id: check-yaml
        args: [--unsafe]
      - id: check-toml
      - id: check-xml

      # Whitespace & line endings
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]

      # Security
      - id: detect-private-key

      # Git integrity
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=102400]

      # Code quality
      - id: debug-statements
      - id: check-ast

  # =========================================================================
  # Python - Ruff (Linting + Formatting)
  # =========================================================================
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.8
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # =========================================================================
  # Python - Type Checking
  # =========================================================================
  # Temporarily disabled: Code needs refactoring for strict type checking.
  # Many files lack proper type hints for compatibility with mypy in strict mode.
  # This will be re-enabled after type annotations are added to the codebase.
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.7.1
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: ["types-PyYAML"]
  #       args: [--ignore-missing-imports]

  # =========================================================================
  # Python - Security
  # =========================================================================
  # Temporarily disabled: bandit 1.7.5 has dependency issues with Python 3.14
  # (missing 'pbr' module). Consider upgrading to bandit 1.8+ or using an
  # alternative security scanner (e.g., semgrep) once compatible versions exist.
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.5
  #   hooks:
  #     - id: bandit
  #       args: [-ll]

  # =========================================================================
  # Shell Scripts
  # =========================================================================
  # Temporarily disabled: Shell scripts need refactoring for ShellCheck compliance
  # Many scripts use word splitting intentionally and have complex structures
  # that require careful refactoring. Will be re-enabled after shell script review.
  # - repo: https://github.com/shellcheck-py/shellcheck-py
  #   rev: v0.9.0.5
  #   hooks:
  #     - id: shellcheck

  # =========================================================================
  # YAML Files
  # =========================================================================
  # Temporarily disabled: Existing YAML files have formatting issues requiring refactor
  # Will be re-enabled after YAML formatting is standardized
  # - repo: https://github.com/adrienverge/yamllint
  #   rev: v1.33.0
  #   hooks:
  #     - id: yamllint
  #       args: [--strict]

  # =========================================================================
  # Markdown Documentation
  # =========================================================================
  # Temporarily disabled: Documentation files have extensive formatting issues
  # Will be re-enabled after markdown files are reformatted per guidelines
  # - repo: https://github.com/igorshubovych/markdownlint-cli
  #   rev: v0.37.0
  #   hooks:
  #     - id: markdownlint
  #       types: [markdown]
