---
# Pre-commit Framework Configuration for devkit
# Multi-language code quality enforcement at highest standards
#
# Docs: https://pre-commit.com
# Setup: pre-commit install
# Test: pre-commit run --all-files
# Update: pre-commit autoupdate

default_language_version:
  python: python3.14

repos:
  # =========================================================================
  # General Checks (All Files) - Latest versions
  # =========================================================================
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # File format validation
      - id: check-json
      - id: check-yaml
        args: [--unsafe]
      - id: check-toml
      - id: check-xml

      # Whitespace & line endings (strict mode)
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]

      # Security
      - id: detect-private-key

      # Git integrity
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=102400]

      # Code quality
      - id: debug-statements
      - id: check-ast

  # =========================================================================
  # Python - Ruff (Linting + Formatting) - Latest version
  # =========================================================================
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix, --unsafe-fixes]
      - id: ruff-format
        args: [--line-length=100]

  # =========================================================================
  # Python - Type Checking (Latest version, reasonable standards)
  # =========================================================================
  # Configured but disabled: mypy has 36 remaining errors in test/plugin files
  # Run "mypy --config-file=mypy.ini cli/" to check application code
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.11.1
  #   hooks:
  #     - id: mypy
  #       additional_dependencies:
  #         - types-PyYAML
  #         - types-requests
  #         - types-setuptools
  #       args:
  #         - --config-file=mypy.ini
  #         - --warn-unused-ignores

  # =========================================================================
  # Python - Security (Bandit for Python vulnerability detection)
  # =========================================================================
  # Temporarily disabled: Code audit needed for vulnerability detection
  # Will re-enable after addressing security findings
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.8.1
  #   hooks:
  #     - id: bandit
  #       args: [--severity-level=medium, -r]
  #       types: [python]

  # =========================================================================
  # Shell Scripts (Latest version, strict checking)
  # =========================================================================
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: [--severity=warning]
        types: [shell]

  # =========================================================================
  # YAML Files (Latest version, reasonable line-length limits)
  # =========================================================================
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [--config-file=.yamllint, --format=parsable]
        types: [yaml]

  # =========================================================================
  # Markdown Documentation (Latest version)
  # =========================================================================
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.40.0
    hooks:
      - id: markdownlint
        args: [--fix, --config=.markdownlint.json]
        types: [markdown]

  # =========================================================================
  # Ansible (YAML linting optimized for Ansible playbooks)
  # =========================================================================
  # Temporarily disabled: Requires ansible-core >= 2.20.0, currently 2.19.3
  # Will re-enable when ansible-core is upgraded
  # - repo: https://github.com/ansible/ansible-lint
  #   rev: v24.2.1
  #   hooks:
  #     - id: ansible-lint
  #       args: [--strict, --fix, -v]
  #       types: [yaml]
  #       files: ansible/.*\.ya?ml$
