- hosts: localhost
  gather_facts: yes
  vars_files:
    - defaults/main.yml
  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']
  roles:
  - role: elliotweiser.osx-command-line-tools
  - role: geerlingguy.mac.homebrew
    tags: ['homebrew']
  - role: geerlingguy.mac.mas
    when: mas_installed_apps or mas_installed_app_ids
    tags: ['mas']
  - role: ansible-vim
    tags: ['vim']
  - role: ansible-tmux
    tags: ['tmux']
  - role: ansible_role_antigen
    tags: ['antigen']
  - role: gantsign.visual-studio-code
    tags: ['code']
  - role: geerlingguy.mac.dock
    when: configure_dock
    tags: ['dock']
  vars:
    #vim
    vim_cleanup: yes
    vim_env: users
    vim_plugin_manager: plug
    vim_emoji_git_integration: no
    vim_neovim: no
    vim_users:
     - "{{ lookup('env','USER') }}"
    vim_colorscheme: mustang
    vim_plugins:
    - { name: 'tpope/vim-sensible' }             # Starting point for vim configuration
    - { name: 'tpope/vim-surround' }             # Starting point for vim configuration
    - { name: 'tpope/vim-fugitive' }             # Starting point for vim configuration
    - { name: 'tpope/vim-commentary' }           # Starting point for vim configuration
    - { name: 'easymotion/vim-easymotion' }      # Starting point for vim configuration
    - { name: 'preservim/nerdtree' }             # Starting point for vim configuration
    - { name: 'morhetz/gruvbox' }                # Starting point for vim configuration
    - { name: 'airblade/vim-gitgutter' }         # Starting point for vim configuration
    - { name: 'vim-airline/vim-airline' }        # Lightweight vimscrip-based statusline
    - { name: 'vim-airline/vim-airline-themes' } # vim-airline theme collection
    - { name: 'edkolev/tmuxline.vim' }           # tmux status line generator with vim-airline integration
    - { name: 'junegunn/vim-emoji' }             # EMOJI
    - { name: 'mhinz/vim-signify' }              # Fast alternative to slow 'airblade/vim-gitgutter' (show git signatures)
    - { name: 'vim-syntastic/syntastic' }        # Syntax Checker for different filetypes (airline integration)
    - { name: 'ryanoasis/vim-devicons' }         # Add icons to plugins (Must be loaded after all other plugins in .vimrc)
    - { name: 'wincent/command-t' }              # Fast "fuzzy" engine for switching buffers, searching etc.
    - { name: 'ctrlpvim/ctrlp.vim' }             # Alternative to command-t (heavy - a lot of features, airline intergration)
    #antigen
    users:
      - username: "{{ lookup('env', 'USER') }}"
        antigen_libraries:
          - name: oh-my-zsh
        antigen_theme:
          name: romkatv/powerlevel10k
        antigen_bundles:
          # Bundles from the default repo (robbyrussell's oh-my-zsh).
          - name: git
          - name: kubectl
          - name: pip
          - name: sudo
          - name: terraform
          - name: vscode
          - name: vi-mode
          - name: web-search
          - name: command-not-found
          - name: kubectx
          - name: kube-ps1
          # Syntax highlighting bundle.
          - name: zsh-syntax-highlighting # `name` is required (any valid file name will do so long as it's unique for the bundles)
            url: https://github.com/zsh-users/zsh-syntax-highlighting
          - name: zsh-autosuggestions
            url: https://github.com/zsh-users/zsh-autosuggestions
          - name: zsh-completions
            url: https://github.com/zsh-users/zsh-completions
        visual_studio_code_extensions:
          - streetsidesoftware.code-spell-checker
          - wholroyd.jinja
          - ms-python.python
          - esbenp.prettier-vscode
#          - CoenraadS.bracket-pair-colorizer-2
          - eamodio.gitlens
          - donjayamanne.githistory
          - idleberg.icon-fonts
          - vscode-icons-team.vscode-icons
          - wayou.vscode-todo-highlight
          - johnpapa.vscode-peacock
          - TabNine.tabnine-vscode
          - christian-kohler.path-intellisense
          - yzhang.markdown-all-in-one
          - aaron-bond.better-comments
          - zhuangtongfa.Material-theme
          - wesbos.theme-cobalt2
          - redhat.vscode-yaml
          - redhat.ansible
          - ms-kubernetes-tools.vscode-kubernetes-tools
          - dbaeumer.vscode-eslint
          - ms-azuretools.vscode-docker
          - github.vscode-pull-request-github
          - ibm.output-colorizer

        visual_studio_code_settings_overwrite: yes
        visual_studio_code_settings: {
          "editor.rulers": [80, 100, 120],
          "editor.renderWhitespace": true,
          "editor.linkedEditing": true,
          "html.autoClosingTags": true,
          "javascript.autoClosingTags": true,
          "typescript.autoClosingTags": true,
          "javascript.suggest.autoImports": true,
          "typescript.suggest.autoImports": true,
          "javascript.updateImportsOnFileMove.enabled": "always",
          "typescript.updateImportsOnFileMove.enabled": "always",
          "editor.bracketPairColorization.enabled": true,
          "editor.guides.bracketPairs" : true,
          "editor.guides.highlightActiveIndentation" : true,
          "editor.guides.bracketPairsHorizontal" : "active",
          "terminal.integrated.fontFamily": "MesloLGS NF",
        }
  tasks:

    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']
    - import_tasks: tasks/exportrc.yml
      when: configure_exportrc
      tags: ['exportrc']
    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']
    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ['post']
    - import_tasks: tasks/gdircolors.yml
      tags: ['gdircolors']
