---
roles:
  - name: cloudalchemy.alertmanager
  - name: cloudalchemy.blackbox-exporter
  - name: cloudalchemy.grafana
  - name: cloudalchemy.node_exporter
  - name: cloudalchemy.prometheus
  - name: cloudalchemy.pushgateway
  - name: cloudalchemy.snmp-exporter
  - name: ome.cadvisor
  - name: nginxinc.nginx
  - name: nginxinc.nginx_config
  - name: elliotweiser.osx-command-line-tools
  - name: geerlingguy.dotfiles
  - name: gantsign.visual-studio-code
  - src: https://github.com/ansible-community/ansible-consul.git
    name: ansible-consul
    scm: git
    version: master
#  - src: https://github.com/openstack/ansible-role-chrony
#    name: ansible-role-chrony
#    scm: git
#    version: master
  - src: https://github.com/vietcgi/ansible-vim
    name: ansible-vim
    scm: git
    version: master
  - src: https://github.com/vietcgi/ansible-tmux
    name: ansible-tmux
    scm: git
    version: master
  - src: https://github.com/vietcgi/ansible_role_antigen
    name: ansible_role_antigen
    scm: git
    version: master
collections:
  - name: community.general
  - name: geerlingguy.mac
