# Shell role - Zsh, Fish, PowerShell configuration

- name: Determine shell environment variables
  ansible.builtin.set_fact:
    shell_choice: "{{ config_shell | default('zsh') }}"
    home_dir: "{{ lookup('env', 'HOME') or '/root' }}"

- name: Install Zsh and plugins
  block:
    - name: Install Zsh
      ansible.builtin.shell: |
        {{ homebrew_prefix }}/bin/brew install zsh zsh-completions
      changed_when: false
      tags: [shell, zsh]

    - name: Install Oh My Zsh
      ansible.builtin.shell: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
      args:
        executable: /bin/bash
        creates: "{{ home_dir }}/.oh-my-zsh"
      tags: [shell, zsh]

    - name: Install Zsh plugins
      ansible.builtin.shell: |
        {{ homebrew_prefix }}/bin/brew install zsh-syntax-highlighting zsh-autosuggestions
      changed_when: false
      tags: [shell, zsh]

    - name: Install Powerlevel10k
      ansible.builtin.git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: "{{ home_dir }}/.oh-my-zsh/custom/themes/powerlevel10k"
        update: yes
      tags: [shell, zsh, theme]

    - name: Install Nerd Font (MesloLGS)
      ansible.builtin.shell: |
        {{ homebrew_prefix }}/bin/brew install --cask font-meslo-lg-nerd-font
      changed_when: false
      tags: [shell, fonts]

    - name: Configure .zshrc
      ansible.builtin.copy:
        content: |
          # Mac-Setup Zsh Configuration
          # Generated by Ansible

          # Export PATH
          export PATH="{{ homebrew_prefix }}/bin:{{ homebrew_prefix }}/sbin:/usr/local/bin"
          export PATH="$PATH:/usr/bin:/bin:/usr/sbin:/sbin"

          # Oh My Zsh
          export ZSH="$HOME/.oh-my-zsh"
          ZSH_THEME="powerlevel10k/powerlevel10k"

          # Plugins
          plugins=(
            git
            docker
            kubectl
            macos
            common-aliases
            copyfile
            direnv
            fzf
            history
            osx
            sudo
            zsh-syntax-highlighting
            zsh-autosuggestions
          )

          source $ZSH/oh-my-zsh.sh

          # GNU tools PATH (macOS)
          {% if is_macos %}
          export PATH="{{ homebrew_prefix }}/opt/gnu-sed/libexec/gnubin:$PATH"
          export PATH="{{ homebrew_prefix }}/opt/gnu-tar/libexec/gnubin:$PATH"
          export PATH="{{ homebrew_prefix }}/opt/grep/libexec/gnubin:$PATH"
          export PATH="{{ homebrew_prefix }}/opt/coreutils/libexec/gnubin:$PATH"
          export PATH="{{ homebrew_prefix }}/opt/findutils/libexec/gnubin:$PATH"
          export PATH="{{ homebrew_prefix }}/opt/gnu-indent/libexec/gnubin:$PATH"
          export PATH="{{ homebrew_prefix }}/opt/gnu-getopt/bin:$PATH"
          export PATH="{{ homebrew_prefix }}/opt/gnu-time/libexec/gnubin:$PATH"
          export PATH="{{ homebrew_prefix }}/opt/gawk/libexec/gnubin:$PATH"
          {% endif %}

          # grc colorizer
          [ -f "{{ homebrew_prefix }}/etc/grc.zsh" ] && source "{{ homebrew_prefix }}/etc/grc.zsh"

          # direnv
          eval "$(direnv hook zsh)"

          # mise (version manager)
          eval "$(mise activate zsh)"

          # Aliases
          alias ll='ls -lh'
          alias la='ls -la'
          alias grep='grep --color=auto'
          alias cat='bat'
          alias ls='lsd'

          # Custom functions
          function cdtemp() {
            cd $(mktemp -d)
          }

        dest: "{{ home_dir }}/.zshrc"
        backup: yes
        mode: '0644'
      tags: [shell, zsh, config]

  when: shell_choice == 'zsh'
  tags: [shell]

- name: Install Fish shell
  block:
    - name: Install Fish
      ansible.builtin.shell: |
        {{ homebrew_prefix }}/bin/brew install fish
      changed_when: false
      tags: [shell, fish]

    - name: Configure Fish config
      ansible.builtin.copy:
        content: |
          # Mac-Setup Fish Configuration

          # PATH
          set -gx PATH {{ homebrew_prefix }}/bin {{ homebrew_prefix }}/sbin /usr/local/bin /usr/bin /bin /usr/sbin /sbin

          # Alias
          alias ll 'ls -lh'
          alias la 'ls -la'
          alias cat 'bat'

        dest: "{{ home_dir }}/.config/fish/config.fish"
        mode: '0644'
        backup: yes
      tags: [shell, fish, config]

  when: shell_choice == 'fish'
  tags: [shell]

- name: Verify shell installation
  ansible.builtin.shell: "{{ item }} --version"
  register: shell_check
  loop:
    - zsh
    - fish
  changed_when: false
  tags: [validation, shell]
