---
# Dotfiles role metadata

galaxy_info:
  author: "Devkit Team"
  description: |
    Deploy dotfiles (configuration files) from the repository to user home directory.
    This role ensures that all configuration files are properly synchronized and maintained.
  license: MIT
  min_ansible_version: "2.10"

  platforms:
    - name: Darwin
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: RedHat
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - dotfiles
    - configuration
    - files

# Role dependencies
# Dotfiles role should run early, after basic setup
dependencies:
  - role: core
    tags:
      - core
      - dotfiles
