---
# export paths.
- name: create .exportrc file
  copy:
    content: "{{ exportrc }}"
    dest: ~/.exportrc
    mode: 0440
- name: Add source ~/.exportrc to .zshrc
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: source ~/.exportrc
    create: yes
