---
# Sudoers configuration.
- name: Copy sudoers configuration into place.
  copy:
    content: "{{ sudoers_custom_config }}"
    dest: /etc/sudoers.d/{{ lookup('env','USER') }}
    mode: 0440
    validate: 'visudo -cf %s'
  become: true
