# Dotfiles role defaults
# Configuration file deployment from repository

# Whether to create backups of existing files
dotfiles_create_backups: true

# Whether to validate configs before deployment
dotfiles_validate: true

# List of dotfiles to deploy (can be overridden)
dotfiles_files_to_sync:
  - src: ".tmux.conf"
    dest: "{{ ansible_user_dir }}/.tmux.conf"
    mode: "0644"
    validate: false
  - src: ".zshrc"
    dest: "{{ ansible_user_dir }}/.zshrc"
    mode: "0644"
    validate: false
  - src: ".direnvrc"
    dest: "{{ ansible_user_dir }}/.direnvrc"
    mode: "0755"
    validate: false
  - src: ".inputrc"
    dest: "{{ ansible_user_dir }}/.inputrc"
    mode: "0644"
    validate: false

# Directories to sync
dotfiles_dirs_to_sync:
  - src: "nvim"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    delete: false
  - src: "ghostty"
    dest: "{{ ansible_user_dir }}/.config/ghostty"
    delete: false
